### ISSUE TITLE
ns parsing error

### ISSUE THREAD

**Issue by oakmac** [oakmac/standard-clojure-style-js#50]
There are two errors here:
1. under no circumstances should the cli.js program have a runtime error caused by the underlying library
2. whatever the actual parsing error is in the underlying library

```txt
✗ /home/oakmac/metabase/src/metabase/shared/util/i18n.clj [0.65ms]
1409 |         nextTokenIsAsSymbol = true
1410 | 
1411 |       // collect the require :as symbol
1412 |       } else if (idx > requireNodeIdx && insideRequireForm && nextTokenIsAsSymbol && isTokenNode2 && isTextNode) {
1413 |         nextTokenIsAsSymbol = false
1414 |         result.requires[activeRequireIdx].as = node.text
               ^
TypeError: undefined is not an object (evaluating 'result.requires[activeRequireIdx]')
      at parseNs (/home/oakmac/standard-clojure-style-js/lib/standard-clojure-style.js:1414:9)
      at format (/home/oakmac/standard-clojure-style-js/lib/standard-clojure-style.js:2696:22)
      at checkFileSync (/home/oakmac/standard-clojure-style-js/cli.js:215:18)
      at reduce (:1:21)
      at processCheckCmd (/home/oakmac/standard-clojure-style-js/cli.js:287:25)
      at /home/oakmac/standard-clojure-style-js/node_modules/yargs/build/index.cjs:1:8991
      at j (/home/oakmac/standard-clojure-style-js/node_modules/yargs/build/index.cjs:1:4956)
      at handleValidationAndGetResult (/home/oakmac/standard-clojure-style-js/node_modules/yargs/build/index.cjs:1:8962)
      at /home/oakmac/standard-clojure-style-js/node_modules/yargs/build/index.cjs:1:58525
      at parse (/home/oakmac/standard-clojure-style-js/node_modules/yargs/build/index.cjs:1:40470)
```

**Comment by oakmac** [comment]
Fixed with [PR-54](https://github.com/oakmac/standard-clojure-style-js/pull/54)
